### ISSUE TITLE
[feature] Add User to Workspace

### ISSUE THREAD

**Issue by luiztauffer** [Tauffer-Consulting/domino#13]
- in the workspace page, invite user by user email: return a success "User was invited" or fail "User does not exist"
- update the relevant database entries, the user-workspace status should be `pending` or something similar
- for the invited user, create a new workspace card with the status `pending`, with the option to accept or refuse
- update the relevant database entries
- add tests for it

**Comment by vinicvaz** [comment]
New `status` column in `user_workspace_associative` with the possible enum values:
- accepted
- rejected
- pending
