### ISSUE TITLE
It didn't deploy in win system?

### ISSUE THREAD

**Issue by wangwei357** [Tauffer-Consulting/domino#132]
When I try deploying in windows 11, it will report  error .

![image](https://github.com/Tauffer-Consulting/domino/assets/77340375/412db073-f225-4c34-8d20-9480d6c21488)

**Comment by luiztauffer** [comment]
hi @wangwei357 could you please describe the installation and run commands you used?

**Comment by vinicvaz** [comment]
Hey @wangwei357 , thanks for you feedback.
Just released a new version that must fix this. 
You can try updating your domino CLI version to `0.5.9`.
Thanks!
