### ISSUE TITLE
[frontend] ReactFlow improvements

### ISSUE THREAD

**Issue by luiztauffer** [Tauffer-Consulting/domino#17]
- [x] Thicken border on selected Node when clicked
- [x] ArrowHead on Edges
- [x] Auto-organize button: https://reactflow.dev/docs/examples/layout/dagre/

**Comment by vinicvaz** [comment]
@nathan-vm @luiztauffer can we close this?

**Comment by luiztauffer** [comment]
let's only close issues once they get merged to `main`, otherwise we list them as completed in the PRs
