### ISSUE TITLE
cross domain issue in local Docker 

### ISSUE THREAD

**Issue by dave-killough** [Tauffer-Consulting/domino#211]
I really like where this is going!!  

I followed the instructions with Docker and got all the way to the point where I successfully created a basic workflow.  Unfortunately, I ran into a cross domain issue when trying to access My Workflows:  

Access to XMLHttpRequest at 'http://localhost:8000/workspaces/2/workflows?page=0&page_size=9' from origin 'http://localhost:3000' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.

I'm using anaconda on windows.  Everything else seems to work ok.   

Thanks!

**Comment by dave-killough** [comment]
It appears that my astro installation in Docker was competing for some of your ports and may be a factor.  I deleted the astro containers, but now the Domino containers are not starting cleanly.  I'm going to try to delete the Domino containers and rerun the pip install.

**Comment by dave-killough** [comment]
It appears that my Astro installation was competing for some of the ports that Domino is using.  I deleted all of the containers in my Docker and will be reinstalling Domino to see if it makes a difference.

**Comment by dave-killough** [comment]
That resolved the error!   Thank you!

**Comment by vanclei** [comment]
hi there,

I had a similar issue, but it was a different error.  

To find out, I used an option --debug:

"domino platform run-compose --debug".  It was the missing .env file with "AIRFLOW_UID=" settings.

https://airflow.apache.org/docs/apache-airflow/stable/howto/docker-compose/index.html

echo -e "AIRFLOW_UID=$(id -u)" > .env

That solved my issue

**Comment by parsa-asgari** [comment]
> hi there,
> 
> I had a similar issue, but it was a different error.
> 
> To find out, I used an option --debug:
> 
> "domino platform run-compose --debug". It was the missing .env file with "AIRFLOW_UID=" settings.
> 
> https://airflow.apache.org/docs/apache-airflow/stable/howto/docker-compose/index.html
> 
> echo -e "AIRFLOW_UID=$(id -u)" > .env
> 
> That solved my issue
Thank you.

Solved my issue as well.
