### ISSUE TITLE
streamline change-test-learn cycle  

### ISSUE THREAD

**Issue by dave-killough** [Tauffer-Consulting/domino#213]
Based on my initial experience in using Domino, not being able to edit workflows will probably be the biggest complaint from my users - more so than logging in twice.  However, I do understand the potential complexities in getting this to work with Airflow.  Using the import to create a new version of the workflow makes it possible to apply revisions, but the lack of testing in the composer will result in users making a lot of revisions.   The change->test->learn cycle needs to be better streamlined, ideally through 1) editing existing workflows, or 2) testing in the composer.

**Comment by luiztauffer** [comment]
Hey @dave-killough, this is an important point, and we’re aware of it. 

One of the features we plan to incorporate in the future will be to allow arguments to be passed (effectively overwritten) per run request, in a way that workflows created through Domino could be consumed as APIs. Once this is in place, we could have a more streamlined way to visually edit arguments per run on the monitoring page.

This is one of the features we’ll be seeking funding for.

**Comment by vinicvaz** [comment]
Moving to
https://github.com/Tauffer-Consulting/domino/issues/219
Updating workflow is the same as editing existing workflows
