### ISSUE TITLE
workflow action publish piece image failed

### ISSUE THREAD

**Issue by lanzhixi** [Tauffer-Consulting/domino#264]
When I created a new piece, I failed to publish the image. The error message is as follows:
{"errorDetail":{"message":"denied: not_found: owner not found"},
![image](https://github.com/Tauffer-Consulting/domino/assets/114967305/e866d6c8-39cd-46e4-b554-846a28fea5d4)
It is worth noting that logging in to github container register was successful, and building the image was also successful, and the error only occurred during the publish piece image.
I guess it is a problem with secrets. Can you tell me how to set it up here?
![image](https://github.com/Tauffer-Consulting/domino/assets/114967305/cf584fe8-98e3-4cc6-8097-14cd2f5aa7fa)
If not, can you share your steps? Thank you so much!

**Comment by vinicvaz** [comment]
Hey @lanzhixi !
Have you configure [this](https://domino-workflows.io/docs/pieces/pieces_repository#:~:text=For%20the%20actions%20to%20run%20successfully%2C%20make%20sure%20that%20under%20your%20repository%20Settings%20%2D%3E%20Action%20%2D%3E%20General%20%2D%3E%20Workflow%20permissions%20the%20option%20Read%20and%20write%20permissions%20is%20selected) in your repository?
Is important to give read and write permission to github workflows to allow it to publish packages to github container registry.

**Comment by lanzhixi** [comment]
Yes, I have given permission. The entire workflow action shows that the execution is successful, but when you click to view the details, it shows that the publish image fails, which is the screenshot above.
![image](https://github.com/Tauffer-Consulting/domino/assets/114967305/6922cc7b-aec0-4c8e-a74d-9c614e02bc73)

**Comment by lanzhixi** [comment]
In my latest attempt, I forked the social_media_domino_pieces repository, modified a few things and recommitted it before triggering the github action. The publish image still failed.[https://github.com/lanzhixi/social_media_domino_pieces/actions/runs/8519357322/job/23333233219](url)
Please take a look where the problem lies，thanks！

**Comment by lanzhixi** [comment]
Latest attempt, I have successfully published the image. Thanks!

**Comment by luiztauffer** [comment]
hey @lanzhixi thank you for reporting this difficulty. Could you tell us what exactly did you do to solve the issue on your end? It might be helpful for our documentation

**Comment by lanzhixi** [comment]
Okay, I'll describe it in detail, hope it's useful to you.
Under the premise of granting relevant permissions, when modifying config.toml, be sure to note that REGISTRY_NAME must be the same as your GitHub account name. My account name originally did not have a "-" to connect it, but I added it artificially, which caused the publish image to fail.
