### ISSUE TITLE
[feature] Array input type

### ISSUE THREAD

**Issue by luiztauffer** [Tauffer-Consulting/domino#28]
Fix GUI rendering of forms containing Array input types that will be generated by models such as this:
```python
from pydantic import BaseModel
from typing import List

class InnerArgModel(BaseModel):
     arg_name: str
     arg_type: (Select with options [string, int, float, bool, fromUpstream])
     arg_value: str

class InputModel(BaseModel):
     new_input_array: List[InnerArgModel]
```

Reference: https://jsonforms.io/examples/array/

![image](https://github.com/Tauffer-Consulting/domino/assets/24541631/5ca24ad6-86db-4b55-a73b-f4156c75b148)

**Comment by nathan-vm** [comment]
Fix in #40
