### ISSUE TITLE
Run locally with Kind error

### ISSUE THREAD

**Issue by lanzhixi** [Tauffer-Consulting/domino#43]
This is a great project. I want to run it locally, but something went wrong. I am a noob in containerization technology. Can you tell me the specific version of the dependencies?
![image](https://github.com/Tauffer-Consulting/domino/assets/114967305/322220a4-8e1f-4d1c-a5c4-f3968114457a)

**Comment by lanzhixi** [comment]
system is Ubuntu 20.04,the rest of the dependencies are all the latest version, the problem may be related to my network environment
![image](https://github.com/Tauffer-Consulting/domino/assets/114967305/ea710b3c-d556-4c55-a9c5-6e9f62316a18)

**Comment by luiztauffer** [comment]
hi @lanzhixi thanks for bringing this into our attention!
we need to review a few tings in the local run with Kind, could you please try to run it with compose, using domino's cli?
ref: https://domino-py.readthedocs.io/en/latest/pages/run_local_compose.html

**Comment by lanzhixi** [comment]
> hi @lanzhixi thanks for bringing this to our attention! we need to review a few tings in the local run with Kind, could you please try to run it with compose, using domino's cli? ref: https://domino-py.readthedocs.io/en/latest/pages/run_local_compose.html

Thank you for your reply. I have tried to run it with docker compose before, and the project can run. However, because I don’t have an account password, I need to register first. I reported an error when I registered, and the registration failed, so I failed to enter the system.

**Comment by lanzhixi** [comment]
Can you give me a test account and password? Thank you very much! ! !

**Comment by luiztauffer** [comment]
@lanzhixi the database runs locally as well when you run with docker or Kind (we are not managing it), this means any account you create is in your own system.
Try creating an account with an email as username (it can be a fake on), this should correctly create an account for you and log you in the system.
We're still working on improving the first time usage experience, thanks for your feedback! And please let us know any other bugs you might find

**Comment by lanzhixi** [comment]
thank you very much
