### ISSUE TITLE
Change Task kwargs

### ISSUE THREAD

**Issue by luiztauffer** [Tauffer-Consulting/domino#50]
Currently we instantiate Tasks like this:

```python
task_SimpleLogPiece_0 = Task(
    dag, 
    task_id='task_SimpleLogPiece_0',
    workflow_shared_storage={
        'source': 'None', 'base_folder': None, 'mode': 'Read/Write', 'provider_options': {}, 
        'storage_repository_id': None
    },
    container_resources={
        'requests': {'cpu': '100.0m', 'memory': '128.0Mi'}, 
        'limits': {'cpu': '100.0m', 'memory': '128.0Mi'}, 
        'use_gpu': False
    },
    piece={
        'name': 'SimpleLogPiece', 
        'source_image': 'ghcr.io/tauffer-consulting/default_domino_pieces:0.0.7-group0', 
        'repository_id': 2
    },
    piece_input_kwargs={
        'input_arg_1': 'piece1', 
        'containerResources': {'cpu': {'min': 100, 'max': 100}, 'memory': {'min': 128, 'max': 128}, 'useGpu': False}
    }
)()
```

I think this can be improved with something like this:
```python
task_SimpleLogPiece_0 = Task(
    dag, 
    task_id='task_SimpleLogPiece_0',
    workspace_id=73,
    workflow_shared_storage={
        'source': 'None', 
        'base_folder': None, 
        'mode': 'Read/Write', 
        'provider_options': {}, 
    },
    container_resources={
        'requests': {'cpu': '100.0m', 'memory': '128.0Mi'}, 
        'limits': {'cpu': '100.0m', 'memory': '128.0Mi'}, 
        'use_gpu': False
    },
    piece={
        'name': 'SimpleLogPiece', 
        'execution_mode': 'docker',  # 'worker'
        'source_image': 'ghcr.io/tauffer-consulting/default_domino_pieces:0.0.7-group0', 
        'repository_url': 'https://github.com/Tauffer-Consulting/default_domino_pieces', 
        'repository_version': '0.2.0',
    },
    piece_input_kwargs={'input_arg_1': 'piece1'}
)()
```

- removed the extra `containerResources` being passed under `piece_input_kwargs` kwarg, since it is already passed under `container_resources` kwarg. Fixed in https://github.com/Tauffer-Consulting/domino/pull/67
- added `workspace_id` a new kwarg to Task
- removed `repository_id` from `piece` kwarg
- added `repository_url` and `repository_version` to `piece` kwarg, which should keep the functionality of Secrets fetching
- added `execution_mode` to `piece` kwarg to allow for the usage of in-worker Pieces
- removed `storage_repository_id` from `workflow_shared_storage` kwarg, we can use a similar strategy here to get the storage access secrets

The change from repository_id to workflow_id will also facilitate a possible future feature of exporting a workflow from one workspace to another

**Comment by vinicvaz** [comment]
@luiztauffer I think we need repository id for fetching secrets and other necessary variables for that piece. The `workflow_id` does not provide this kind of information directly. Using `repository_name` instead can make the request ambiguous since the name is not unique across multiple users.

**Comment by vinicvaz** [comment]
To implement these changes we'll need to:
- [ ] Refactor `get_secrets` endpoint to accept workspace_id and repository_name
- [ ] Refactor custom classes of `DockerOperator` and `KubernetesPodOperator` for using these values.
- [ ] Update method that generate dag from json. This will be updated anyway with the last update changes on frontend.

**Comment by luiztauffer** [comment]
@vinicvaz do you think a similar change could be made to remove `storage_repository_id` and instead use the `workspace_id` + `source`? Since we expect that storage sources names will be unique within the same workspace
```python
workflow_shared_storage={
    'source': 'None', 
    'base_folder': None, 
    'mode': 'Read/Write', 
    'provider_options': {}, 
    'storage_repository_id': None
},
```
