### ISSUE TITLE
data flow

### ISSUE THREAD

**Issue by lanzhixi** [Tauffer-Consulting/domino#66]
This is a great project and I have some doubts about it. A workflow is composed of multiple piece links. Is the output of the previous piece the input of the next piece? Or these pieces are working alone without intersection. If not, will we support data flow between pieces in the future?thanks for your answer.

**Comment by luiztauffer** [comment]
hey @lanzhixi great question! Yes, the output of any given Piece could be used as an input to any other Pieces, as long as their types match! This should be easily done when we merge the upcoming changes in the `dev` branch

**Comment by lanzhixi** [comment]
Thank you very much for your answer, I understand
