### ISSUE TITLE
upstreamId key with wrong values

### ISSUE THREAD

**Issue by vinicvaz** [Tauffer-Consulting/domino#69]
When a node field is using `fromUpstream` argument the `upstreamId` key is holding wrong values.
The value should be the id from the upstream node where the argument is comming but it is saving the own node id.

Example image:
![image](https://github.com/Tauffer-Consulting/domino/assets/50757601/f6ed4f31-4a8f-488f-9dea-8d95f4ce1572)
The value in `upstreamId` should be `4_ea95...`

**Comment by nathan-vm** [comment]
fix on #67
