### ISSUE TITLE
Piece connection issues

### ISSUE THREAD

**Issue by lanzhixi** [Tauffer-Consulting/domino#73]
1. If the output type of the previous piece does not have the input type required by the next piece, consider whether there is no connection between the two? As shown: the first piece outputs the string type, while the next piece requires the int type, and the two are actually not related.Whether to consider adding a judgment before connecting, if it does not meet, it cannot be connected.
![image](https://github.com/Tauffer-Consulting/domino/assets/114967305/d407c372-1dff-4c98-8762-5deb307b759c)

2. It should be more convenient to have arrows when connecting.

These are just some of my suggested modifications. Thank you so much.

**Comment by luiztauffer** [comment]
thanks for your suggestions @lanzhixi !

Although you're right about the Pieces not being able to share data in case they don't produce/consume the same data types, connecting them is still important IF you want to create a DAG, that is, the downstream Piece will only execute IF the upstream Piece executed successfully. If this sort of execution order is important in your workflow, then it is still important to connect them.

For easy edition of data types between Pieces, e.g. if you want to transform an upstream's output to fit a downstream's input type, consider using the CustomPythonPiece! It is already available in `dev` branch, soon we'll release it as well.

2. We totally agree, and we'll look into ways to facilitate connection and show more explicitly the direction arrow
