### ISSUE TITLE
Conditional dependencies

### ISSUE THREAD

**Issue by luiztauffer** [Tauffer-Consulting/domino#76]
Re-organize dependencies. 

Some of them won't need to be installed in every usage mode, e.g.:
- Pieces images won't need `PyGithub`, `docker`, `kubernetes`
- Airflow+Domino images won't need `PyGithub`, `bottle`
- User's that will only use the cli to create platform locally or to dry run Pieces probably won't need some of these 

We don't seem to need `fsspec` anywhere.

Also, we might want to migrate to use `pyproject.toml`

**Comment by vinicvaz** [comment]
@luiztauffer can we close this?

**Comment by luiztauffer** [comment]
@vinicvaz once we merge to main
