### ISSUE TITLE
[BUG] - Create workflow with shared storage

### ISSUE THREAD

**Issue by vinicvaz** [Tauffer-Consulting/domino#97]
When trying to create a new workflow that uses S3 shared storage but some of the required secrets are not filled (access_key or secret_key) the validation is show "Resource not found", we must show a custom message.

![image](https://github.com/Tauffer-Consulting/domino/assets/50757601/9cfd813a-56b5-431b-9e5b-9da5a3274574)

**Comment by luiztauffer** [comment]
@vinicvaz is this fixed already in `dev`?

**Comment by vinicvaz** [comment]
@luiztauffer I don't think so.

**Comment by nathan-vm** [comment]
>Also, I think there are other error notifications that are showing with dictionary and details

Not sure about the current reported error, but definitely we are not handling income api errors properly, working on it rn
